#!/bin/sh
LOGO_DIR=~/.git-templates/logos/
LOGO=git.png
if [[ $1 == heroku* ]]; then
  LOGO=heroku.png
fi
/usr/local/bin/terminal-notifier -title "Git" -group "git-notify" -appIcon "$LOGO_DIR$LOGO" -message "Commit done"
